SUBJECT_SUGGESTIONS = {
    # === MATHEMATICS (22 variants) ===
    "mathematics": "Mathematics",
    "maths": "Mathematics",
    "math": "Mathematics",
    "mathematic": "Mathematics",
    "mths": "Mathematics",
    "mth": "Mathematics",
    "mat": "Mathematics",
    "mats": "Mathematics",
    "core math": "Mathematics",
    "core maths": "Mathematics",
    "core mathematics": "Mathematics",
    "general math": "Mathematics",
    "general maths": "Mathematics",
    "general mathematics": "Mathematics",
    "gen math": "Mathematics",
    "gen maths": "Mathematics",
    "gen mathematics": "Mathematics",
    "mathematical": "Mathematics",
    "mathematix": "Mathematics",
    "mathamatics": "Mathematics",
    "mathmatics": "Mathematics",
    "mathe": "Mathematics",

    # === ENGLISH LANGUAGE (21 variants) ===
    "english language": "English Language",
    "english": "English Language",
    "eng": "English Language",
    "eng lang": "English Language",
    "englishlang": "English Language",
    "englanguage": "English Language",
    "el": "English Language",
    "eng language": "English Language",
    "english lng": "English Language",
    "englnag": "English Language",
    "english-language": "English Language",
    "use of english": "English Language",
    "use of eng": "English Language",
    "general english": "English Language",
    "gen english": "English Language",
    "engish": "English Language",
    "englsh": "English Language",
    "engli": "English Language",
    "english l": "English Language",
    "englishla": "English Language",
    "engllish": "English Language",

    # === PHYSICS (20 variants) ===
    "physics": "Physics",
    "physic": "Physics",
    "phy": "Physics",
    "phys": "Physics",
    "phsyics": "Physics",
    "phycis": "Physics",
    "phsics": "Physics",
    "pure physics": "Physics",
    "physx": "Physics",
    "phyics": "Physics",
    "phisics": "Physics",
    "phisic": "Physics",
    "pyhsics": "Physics",
    "physc": "Physics",
    "physci": "Physics",
    "phyiscs": "Physics",
    "phisix": "Physics",
    "physik": "Physics",
    "physiz": "Physics",
    "phizics": "Physics",

    # === CHEMISTRY (20 variants) ===
    "chemistry": "Chemistry",
    "chem": "Chemistry",
    "che": "Chemistry",
    "chems": "Chemistry",
    "chemist": "Chemistry",
    "chm": "Chemistry",
    "chms": "Chemistry",
    "chmisty": "Chemistry",
    "chemisry": "Chemistry",
    "chemestry": "Chemistry",
    "chemsitry": "Chemistry",
    "pure chemistry": "Chemistry",
    "chemi": "Chemistry",
    "chemis": "Chemistry",
    "chmeistry": "Chemistry",
    "cemistry": "Chemistry",
    "cem": "Chemistry",
    "chemstry": "Chemistry",
    "chemisrt": "Chemistry",
    "chemistery": "Chemistry",

    # === BIOLOGY (20 variants) ===
    "biology": "Biology",
    "bio": "Biology",
    "biol": "Biology",
    "biolg": "Biology",
    "pure biology": "Biology",
    "bilogy": "Biology",
    "bioology": "Biology",
    "biolo": "Biology",
    "biological": "Biology",
    "biological science": "Biology",
    "bioscience": "Biology",
    "boiology": "Biology",
    "bg": "Biology",
    "bly": "Biology",
    "biolgy": "Biology",
    "bioo": "Biology",
    "biologi": "Biology",
    "biolog": "Biology",
    "bology": "Biology",
    "byology": "Biology",

    # === ECONOMICS (20 variants) ===
    "economics": "Economics",
    "econ": "Economics",
    "econs": "Economics",
    "eco": "Economics",
    "ecn": "Economics",
    "ecns": "Economics",
    "economis": "Economics",
    "econmics": "Economics",
    "econimics": "Economics",
    "ecomonics": "Economics",
    "eccnomics": "Economics",
    "econo": "Economics",
    "econnomics": "Economics",
    "econimcs": "Economics",
    "eocnomics": "Economics",
    "econoics": "Economics",
    "econmcs": "Economics",
    "ecknomics": "Economics",
    "exonomics": "Economics",
    "ekonomics": "Economics",

    # === GOVERNMENT (20 variants) ===
    "government": "Government",
    "govt": "Government",
    "gov": "Government",
    "gove": "Government",
    "govment": "Government",
    "goverment": "Government",
    "gvt": "Government",
    "political science": "Government",
    "poli sci": "Government",
    "polisci": "Government",
    "pol science": "Government",
    "governmnt": "Government",
    "govrenment": "Government",
    "govrnment": "Government",
    "govnt": "Government",
    "govement": "Government",
    "gvmt": "Government",
    "govv": "Government",
    "governemnt": "Government",
    "govremernt": "Government",

    # === LITERATURE IN ENGLISH (20 variants) ===
    "literature in english": "Literature in English",
    "literature": "Literature in English",
    "lit": "Literature in English",
    "lit in english": "Literature in English",
    "english literature": "Literature in English",
    "eng lit": "Literature in English",
    "english lit": "Literature in English",
    "literature-in-english": "Literature in English",
    "lit in eng": "Literature in English",
    "lit-in-eng": "Literature in English",
    "litineng": "Literature in English",
    "literatures": "Literature in English",
    "literatur": "Literature in English",
    "litrature": "Literature in English",
    "literture": "Literature in English",
    "litra": "Literature in English",
    "eng literature": "Literature in English",
    "lit in english language": "Literature in English",
    "lit language": "Literature in English",
    "literature in eng": "Literature in English",

    # === CHRISTIAN RELIGIOUS STUDIES (20 variants) ===
    "christian religious studies": "Christian Religious Studies",
    "crs": "Christian Religious Studies",
    "crk": "Christian Religious Studies",
    "christian religious knowledge": "Christian Religious Studies",
    "christian religion": "Christian Religious Studies",
    "christian religious": "Christian Religious Studies",
    "crs studies": "Christian Religious Studies",
    "crk knowledge": "Christian Religious Studies",
    "christian study": "Christian Religious Studies",
    "christian knowledge": "Christian Religious Studies",
    "christain religious studies": "Christian Religious Studies",
    "christain religion": "Christian Religious Studies",
    "christan religious studies": "Christian Religious Studies",
    "crst": "Christian Religious Studies",
    "christian values": "Christian Religious Studies",
    "crs/crk": "Christian Religious Studies",
    "religious studies crs": "Christian Religious Studies",
    "rel studies crs": "Christian Religious Studies",
    "christain religious knowledge": "Christian Religious Studies",
    "christan religious knowledge": "Christian Religious Studies",

    # === ISLAMIC RELIGIOUS STUDIES (20 variants) ===
    "islamic religious studies": "Islamic Religious Studies",
    "irs": "Islamic Religious Studies",
    "irk": "Islamic Religious Studies",
    "islamic religious knowledge": "Islamic Religious Studies",
    "islamic studies": "Islamic Religious Studies",
    "islamic religion": "Islamic Religious Studies",
    "islamics": "Islamic Religious Studies",
    "islamic knowledge": "Islamic Religious Studies",
    "islam religion": "Islamic Religious Studies",
    "islam studies": "Islamic Religious Studies",
    "irs studies": "Islamic Religious Studies",
    "irk knowledge": "Islamic Religious Studies",
    "islamic religious": "Islamic Religious Studies",
    "islamics studies": "Islamic Religious Studies",
    "islamiat": "Islamic Religious Studies",
    "islamiyya": "Islamic Religious Studies",
    "religious studies irs": "Islamic Religious Studies",
    "islamic ed": "Islamic Religious Studies",
    "islamic education": "Islamic Religious Studies",
    "islamic rel": "Islamic Religious Studies",

    # === GEOGRAPHY (20 variants) ===
    "geography": "Geography",
    "geo": "Geography",
    "geog": "Geography",
    "geogr": "Geography",
    "geografy": "Geography",
    "geogaphy": "Geography",
    "geogrpahy": "Geography",
    "georgaphy": "Geography",
    "georaphy": "Geography",
    "geogrophy": "Geography",
    "geograhpy": "Geography",
    "pure geography": "Geography",
    "gg": "Geography",
    "geogry": "Geography",
    "geography sci": "Geography",
    "geography science": "Geography",
    "geogrphy": "Geography",
    "geogafy": "Geography",
    "geogrephy": "Geography",
    "geogriphy": "Geography",

    # === HISTORY (20 variants) ===
    "history": "History",
    "hist": "History",
    "histry": "History",
    "hstory": "History",
    "hiztory": "History",
    "historie": "History",
    "historical": "History",
    "historical studies": "History",
    "histroy": "History",
    "his": "History",
    "hst": "History",
    "histori": "History",
    "historys": "History",
    "world history": "History",
    "historiology": "History",
    "hisstory": "History",
    "hixtory": "History",
    "histor": "History",
    "histra": "History",
    "history studies": "History",

    # === COMMERCE (20 variants) ===
    "commerce": "Commerce",
    "comm": "Commerce",
    "com": "Commerce",
    "commerse": "Commerce",
    "commerc": "Commerce",
    "commerces": "Commerce",
    "comerce": "Commerce",
    "comerse": "Commerce",
    "comms": "Commerce",
    "commercial": "Commerce",
    "commercial studies": "Commerce",
    "comerec": "Commerce",
    "cmc": "Commerce",
    "cmrc": "Commerce",
    "commerece": "Commerce",
    "commercie": "Commerce",
    "commers": "Commerce",
    "comercio": "Commerce",
    "commrec": "Commerce",
    "commerse studies": "Commerce",

    # === ACCOUNTING (20 variants) ===
    "accounting": "Accounting",
    "acc": "Accounting",
    "acct": "Accounting",
    "account": "Accounting",
    "accounts": "Accounting",
    "accting": "Accounting",
    "accountancy": "Accounting",
    "acounting": "Accounting",
    "acount": "Accounting",
    "accnt": "Accounting",
    "accnting": "Accounting",
    "act": "Accounting",
    "acting": "Accounting",
    "financial accounting": "Financial Accounting",
    "fin acc": "Accounting",
    "fin acct": "Accounting",
    "acctcy": "Accounting",
    "acco": "Accounting",
    "accou": "Accounting",
    "accountig": "Accounting",

    # === AGRICULTURAL SCIENCE (20 variants) ===
    "agricultural science": "Agricultural Science",
    "agric": "Agricultural Science",
    "agric science": "Agricultural Science",
    "agri": "Agricultural Science",
    "agriculture": "Agricultural Science",
    "agric sci": "Agricultural Science",
    "ag science": "Agricultural Science",
    "ag sci": "Agricultural Science",
    "agr science": "Agricultural Science",
    "agr sci": "Agricultural Science",
    "agricultural": "Agricultural Science",
    "argic": "Agricultural Science",
    "argic science": "Agricultural Science",
    "agricultural sci": "Agricultural Science",
    "aggric": "Agricultural Science",
    "agrc": "Agricultural Science",
    "agr": "Agricultural Science",
    "farming science": "Agricultural Science",
    "agricul": "Agricultural Science",
    "agricutlure": "Agricultural Science",

    # === YORUBA (20 variants) ===
    "yoruba": "Yoruba",
    "yor": "Yoruba",
    "yru": "Yoruba",
    "yrb": "Yoruba",
    "yorb": "Yoruba",
    "yorub": "Yoruba",
    "yorubas": "Yoruba",
    "yoruba language": "Yoruba",
    "yor lang": "Yoruba",
    "yoruba lang": "Yoruba",
    "yorubaa": "Yoruba",
    "yuruba": "Yoruba",
    "yorubai": "Yoruba",
    "yorubah": "Yoruba",
    "yroba": "Yoruba",
    "yorouba": "Yoruba",
    "yoruban": "Yoruba",
    "yorb lang": "Yoruba",
    "yorubha": "Yoruba",
    "yooruba": "Yoruba",

    # === HAUSA (20 variants) ===
    "hausa": "Hausa",
    "hau": "Hausa",
    "haua": "Hausa",
    "haus": "Hausa",
    "hausas": "Hausa",
    "hausa language": "Hausa",
    "hau lang": "Hausa",
    "hausa lang": "Hausa",
    "the hausa": "Hausa",
    "haussa": "Hausa",
    "hawsa": "Hausa",
    "howsa": "Hausa",
    "haousa": "Hausa",
    "hausan": "Hausa",
    "hasua": "Hausa",
    "huasa": "Hausa",
    "hausah": "Hausa",
    "hauz": "Hausa",
    "hauza": "Hausa",
    "hoosa": "Hausa",

    # === IGBO (20 variants) ===
    "igbo": "Igbo",
    "igb": "Igbo",
    "ibo": "Igbo",
    "ibos": "Igbo",
    "igbos": "Igbo",
    "igbo language": "Igbo",
    "igb lang": "Igbo",
    "igbo lang": "Igbo",
    "ibo lang": "Igbo",
    "igboo": "Igbo",
    "igboh": "Igbo",
    "eegbo": "Igbo",
    "igbho": "Igbo",
    "igbu": "Igbo",
    "egbo": "Igbo",
    "igb0": "Igbo",
    "isbo": "Igbo",
    "igob": "Igbo",
    "igboc": "Igbo",
    "igboon": "Igbo",

    # === FRENCH (20 variants) ===
    "french": "French",
    "fre": "French",
    "frn": "French",
    "frch": "French",
    "fren": "French",
    "french language": "French",
    "fre lang": "French",
    "french lang": "French",
    "frensh": "French",
    "frinch": "French",
    "pure french": "French",
    "frenh": "French",
    "frenc": "French",
    "ferench": "French",
    "frenchie": "French",
    "frnch": "French",
    "fra": "French",
    "francais": "French",
    "français": "French",
    "frenhc": "French",

    # === CIVIC EDUCATION (20 variants) ===
    "civic education": "Civic Education",
    "civic": "Civic Education",
    "civic edu": "Civic Education",
    "civics": "Civic Education",
    "civic ed": "Civic Education",
    "civic educ": "Civic Education",
    "civic eduation": "Civic Education",
    "civic eductn": "Civic Education",
    "cvc": "Civic Education",
    "cvc edu": "Civic Education",
    "civic studies": "Civic Education",
    "civic-education": "Civic Education",
    "civicedu": "Civic Education",
    "civick": "Civic Education",
    "civik": "Civic Education",
    "civic education studies": "Civic Education",
    "social civic": "Civic Education",
    "civic end": "Civic Education",
    "c.edu": "Civic Education",
    "civiced": "Civic Education",

    # === FURTHER MATHEMATICS (20 variants) ===
    "further mathematics": "Further Mathematics",
    "further maths": "Further Mathematics",
    "further math": "Further Mathematics",
    "fmath": "Further Mathematics",
    "fm": "Further Mathematics",
    "f maths": "Further Mathematics",
    "f math": "Further Mathematics",
    "f mathematics": "Further Mathematics",
    "further mths": "Further Mathematics",
    "further mth": "Further Mathematics",
    "furth math": "Further Mathematics",
    "furth maths": "Further Mathematics",
    "add math": "Further Mathematics",
    "add maths": "Further Mathematics",
    "additional mathematics": "Further Mathematics",
    "additional maths": "Further Mathematics",
    "furter maths": "Further Mathematics",
    "futher maths": "Further Mathematics",
    "furthermaths": "Further Mathematics",
    "furthermath": "Further Mathematics",

    # === INSURANCE (20 variants) ===
    "insurance": "Insurance",
    "ins": "Insurance",
    "insur": "Insurance",
    "insu": "Insurance",
    "insrance": "Insurance",
    "insuranc": "Insurance",
    "insure": "Insurance",
    "insurances": "Insurance",
    "insurnace": "Insurance",
    "insuarance": "Insurance",
    "insuarence": "Insurance",
    "insurace": "Insurance",
    "inshurance": "Insurance",
    "inssurance": "Insurance",
    "insurans": "Insurance",
    "insrnance": "Insurance",
    "insurnce": "Insurance",
    "insrt": "Insurance",
    "insuara": "Insurance",
    "insurancy": "Insurance",

    # === HOME ECONOMICS (20 variants) ===
    "home economics": "Home Economics",
    "home econ": "Home Economics",
    "he": "Home Economics",
    "home ec": "Home Economics",
    "home economics science": "Home Economics",
    "homecon": "Home Economics",
    "homeecon": "Home Economics",
    "home eco": "Home Economics",
    "home econs": "Home Economics",
    "home_econ": "Home Economics",
    "home-econ": "Home Economics",
    "home economics studies": "Home Economics",
    "home science": "Home Economics",
    "catering": "Home Economics",
    "clothing and textiles": "Home Economics",
    "home management": "Home Economics",
    "hm econ": "Home Economics",
    "hm economics": "Home Economics",
    "home econmics": "Home Economics",
    "home eccnomics": "Home Economics",

    # === MUSIC (20 variants) ===
    "music": "Music",
    "mus": "Music",
    "msc": "Music",
    "musc": "Music",
    "musics": "Music",
    "musical": "Music",
    "musical arts": "Music",
    "music art": "Music",
    "muzic": "Music",
    "muzik": "Music",
    "musick": "Music",
    "musique": "Music",
    "musi": "Music",
    "musice": "Music",
    "mizic": "Music",
    "mysic": "Music",
    "musica": "Music",
    "musec": "Music",
    "muisic": "Music",
    "musci": "Music",

    # === ANIMAL HUSBANDRY (20 variants) ===
    "animal husbandry": "Animal Husbandry",
    "animal": "Animal Husbandry",
    "husbandry": "Animal Husbandry",
    "ah": "Animal Husbandry",
    "animal husband": "Animal Husbandry",
    "animal husb": "Animal Husbandry",
    "anim husbandry": "Animal Husbandry",
    "anim husb": "Animal Husbandry",
    "animal husbndry": "Animal Husbandry",
    "animal husbantry": "Animal Husbandry",
    "animal hasbandry": "Animal Husbandry",
    "animal husbanry": "Animal Husbandry",
    "animal husbundry": "Animal Husbandry",
    "animal science": "Animal Husbandry",
    "livestock": "Animal Husbandry",
    "livestock farming": "Animal Husbandry",
    "animal production": "Animal Husbandry",
    "anim sci": "Animal Husbandry",
    "animal-husbandry": "Animal Husbandry",
    "animal_husbandry": "Animal Husbandry",

    # === DATA PROCESSING (20 variants) ===
    "data processing": "Data Processing",
    "data": "Data Processing",
    "data process": "Data Processing",
    "dp": "Data Processing",
    "data processing science": "Data Processing",
    "data proc": "Data Processing",
    "dataprocessing": "Data Processing",
    "dataprocess": "Data Processing",
    "data pro": "Data Processing",
    "d processing": "Data Processing",
    "data prcessing": "Data Processing",
    "data proccesing": "Data Processing",
    "data pacesing": "Data Processing",
    "computer data": "Data Processing",
    "data prc": "Data Processing",
    "data mgt": "Data Processing",
    "data management": "Data Processing",
    "dt processing": "Data Processing",
    "d.p": "Data Processing",
    "dataproc": "Data Processing",
}


def suggest_correction(unknown_subject):
    """
    Return the correct canonical subject name if matched, or None.
    Dynamically strips punctuation and handles divider changes.
    """
    if not isinstance(unknown_subject, str):
        return None

    # Step 1: Clean basic whitespace and strip all periods (e.g., 'F.M.' -> 'fm')
    cleaned_input = unknown_subject.lower().strip().replace(".", "")

    # Step 2: Direct Dictionary Matching
    if cleaned_input in SUBJECT_SUGGESTIONS:
        return SUBJECT_SUGGESTIONS[cleaned_input]

    # Step 3: Algorithmic fallback normalization for symbols (dashes, underscores)
    normalized_input = cleaned_input.replace("-", " ").replace("_", " ")
    if normalized_input in SUBJECT_SUGGESTIONS:
        return SUBJECT_SUGGESTIONS[normalized_input]

    return None